spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: password

iex:
    host: https://cloud.iexapis.com/v1
    token: ${IEX_PUB_TOKEN}

httpClient:
    poolMaxTotal: 50
    maxPerRoute: 50
